language: java
jdk: oraclejdk8
sudo: false
script: mvn package
deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: PSUx7UFJa8XqnOH2MTbldShS3ty8laJV/mZPGbWaa4LPWMY2MSHEb4WKsUdfbmH/ea8/nk8yuaqs/myoQrRioPpJN/YrMbb1BajVEaVhXU5A/WvvKs7VhJQBwhzvEdLzSHLQ2lGKYXF2JqXRnUMG5vj2GB/+PIEVSX77GO4SExMmW3ijzaqYD9XWThkFxAMk7cCE6M+eMwQmlQSZW4dpCSUxxkQUp4B+zQ5tqiIAIqBbv9BVycgLxQrgDNjSvE9ghEYAvMl1Q19oSV4jtq3uAFxef7+Mpd9rJPPitWQBSrd7AacvJZfHLKhZiwZm8FiRPNRWE0dkcaBSMj7WR/vX2wCL7TJM97ItQx/H1hxbBt0FPTabfeNdTU9N8qyTYoYkc5vNgDo/7GUTo74UhMaCEbNFAAipMbeI7cxjsC8QMUpGiUuaCeY/4K0EKlv5o9gJeIu5rSr3H/nmDzuGzszGEL6IrrexV4J1dFoT4REFbAJ6T29OMBhfz0JUb0ispWPA1BTRkAgwBSNfZFsoXloFI3YLUZUjCa3hEo7V6UO50e0F7DdyrNshM3c57L2nTw/JuZlPHkHPw9ycJ/Vhjg3ZhYNvJpl8h08EdVYnEzifyZW9IZC2/7vVlbJ1Y1R+PomT4LzAi2CNmL4reu5VElVfumd7msQyxajrSrBunrCLgTI=
  file_glob: true  
  file: target/pop-web-controller*.jar
  on:
    repo: snichola/pop-web-controller
    branch: master
    tags: true